import { EventListing } from '../../interfaces/event.interface';

const sondeka = {
  name: 'Sondeka Ltd',
  initial: 'S',
  verified: true,
  eventsHosted: 42,
  rating: 4.8,
  respondsWithin: 'a day',
};

export const MOCK_EVENTS: EventListing[] = [
  {
    id: 'nairobi-music-festival-2026',
    title: 'Nairobi Music Festival 2026',
    category: 'Music',
    dateTime: '2026-08-29T18:00:00',
    endTime: '2026-08-30T02:00:00',
    venue: { name: 'Uhuru Gardens', address: 'Langata Road, Nairobi · Free parking · Wheelchair accessible' },
    priceFrom: 1500,
    coverGradient: ['#2E1065', '#7C3AED'],
    tags: ['Afro house', 'Live band', 'Outdoor', '18+'],
    about: [
      'Nairobi Music Festival returns for its fourth year with three stages of Afro house, live bands and headline sets, running from sunset well past midnight.',
      'Expect a full night of Nairobi’s best DJs and live acts alongside international headliners, food trucks and a dedicated chill-out zone.',
    ],
    schedule: [
      { time: '5:00 PM', title: 'Gates open', detail: 'Main entrance, Uhuru Gardens' },
      { time: '6:00 PM', title: 'Opening sets', detail: 'Amapiano stage' },
      { time: '8:30 PM', title: 'Nyota Band — live set' },
      { time: '10:00 PM', title: 'Ayira — headline set' },
      { time: '12:30 AM', title: 'Afterglow', detail: 'DJ Kalu closes out the main stage' },
    ],
    lineup: [
      { name: 'Ayira', role: 'Headliner' },
      { name: 'DJ Kalu', role: 'Amapiano' },
      { name: 'Nyota Band', role: 'Live set' },
      { name: 'Maua', role: 'Afro house' },
    ],
    organizer: sondeka,
    ticketTiers: [
      { id: 'early', name: 'Early Bird', price: 1500, description: 'Limited release · entry from 5 PM', remaining: 40 },
      { id: 'regular', name: 'Regular', price: 2500, description: 'General admission, all stages', remaining: 312, popular: true },
      { id: 'vip', name: 'VIP', price: 7500, description: 'Front stage deck · free bar · fast lane', remaining: 18 },
      { id: 'group', name: 'Group of 5', price: 6500, description: 'Five general-admission passes', remaining: 0, soldOut: true },
    ],
    status: 'lowstock',
    featured: true,
  },
  {
    id: 'nairobi-tech-summit-2026',
    title: 'Nairobi Tech Summit 2026',
    category: 'Technology',
    dateTime: '2026-09-12T08:30:00',
    endTime: '2026-09-13T17:00:00',
    venue: { name: 'KICC', address: 'City Hall Way, Nairobi · Delegate parking on-site' },
    priceFrom: 3500,
    coverGradient: ['#052E3A', '#0891B2'],
    tags: ['AI', 'Startups', 'Networking'],
    about: [
      'Two days of keynotes, workshops and founder panels covering East Africa’s fastest-growing tech scene.',
      'Includes access to the startup expo floor and evening networking mixer both days.',
    ],
    schedule: [
      { time: '8:30 AM', title: 'Registration & breakfast' },
      { time: '9:30 AM', title: 'Opening keynote' },
      { time: '1:00 PM', title: 'Founder panel: scaling in East Africa' },
      { time: '5:30 PM', title: 'Networking mixer', detail: 'Expo floor' },
    ],
    lineup: [
      { name: 'Amina Yusuf', role: 'Keynote — AI in Africa' },
      { name: 'Brian Otieno', role: 'Panel moderator' },
    ],
    organizer: sondeka,
    ticketTiers: [
      { id: 'delegate', name: 'Delegate', price: 3500, description: 'Both days · expo + all talks', remaining: 210, popular: true },
      { id: 'startup', name: 'Startup', price: 1800, description: 'Discounted rate for founders', remaining: 60 },
      { id: 'vip', name: 'VIP', price: 9000, description: 'Front-row + speaker dinner', remaining: 12 },
    ],
    status: 'onsale',
    featured: true,
  },
  {
    id: 'afrofuture-live',
    title: 'AfroFuture Live',
    category: 'Music',
    dateTime: '2026-09-05T19:00:00',
    endTime: '2026-09-06T01:00:00',
    venue: { name: 'Carnivore Grounds', address: 'Langata Road, Nairobi' },
    priceFrom: 2000,
    coverGradient: ['#4C0519', '#E11D48'],
    tags: ['Afrobeats', 'Live band'],
    about: ['A night of Afrobeats and Amapiano headlined by some of the continent’s biggest rising acts.'],
    schedule: [
      { time: '7:00 PM', title: 'Gates open' },
      { time: '9:00 PM', title: 'Main stage begins' },
    ],
    lineup: [{ name: 'Tempo Rise', role: 'Headliner' }],
    organizer: sondeka,
    ticketTiers: [
      { id: 'ga', name: 'General', price: 2000, description: 'General admission', remaining: 400, popular: true },
      { id: 'vip', name: 'VIP', price: 6000, description: 'VIP deck + fast lane', remaining: 50 },
    ],
    status: 'onsale',
    featured: true,
  },
  {
    id: 'comedy-night',
    title: 'Comedy Night',
    category: 'Comedy',
    dateTime: '2026-08-22T19:30:00',
    venue: { name: 'The Alchemist', address: 'Westlands, Nairobi' },
    priceFrom: 1000,
    coverGradient: ['#3B3B44', '#8A8A9E'],
    tags: ['Stand-up', '18+'],
    about: ['An evening of stand-up from Nairobi’s sharpest comedians.'],
    schedule: [{ time: '7:30 PM', title: 'Doors open' }, { time: '8:00 PM', title: 'Show starts' }],
    lineup: [{ name: 'Kevo Mash', role: 'Host' }],
    organizer: sondeka,
    ticketTiers: [{ id: 'ga', name: 'General', price: 1000, description: 'General admission', remaining: 0, soldOut: true }],
    status: 'soldout',
  },
  {
    id: 'startup-networking-night',
    title: 'Startup Networking Night',
    category: 'Networking',
    dateTime: '2026-08-27T18:00:00',
    venue: { name: 'iHub', address: 'Senteu Plaza, Galana Road, Nairobi' },
    priceFrom: 0,
    coverGradient: ['#0F172A', '#475569'],
    tags: ['Founders', 'Investors'],
    about: ['A casual mixer for founders, operators and early-stage investors — no pitching required.'],
    schedule: [{ time: '6:00 PM', title: 'Doors open' }, { time: '6:30 PM', title: 'Lightning intros' }],
    lineup: [],
    organizer: sondeka,
    ticketTiers: [{ id: 'ga', name: 'Free entry', price: 0, description: 'RSVP required', remaining: 120 }],
    status: 'free',
  },
  {
    id: 'creative-workshop',
    title: 'Creative Workshop',
    category: 'Workshops',
    dateTime: '2026-09-01T10:00:00',
    venue: { name: 'GoDown Arts Centre', address: 'Dunga Road, Industrial Area, Nairobi' },
    priceFrom: 2500,
    coverGradient: ['#1E1B4B', '#6366F1'],
    tags: ['Hands-on', 'Small group'],
    about: ['A full-day hands-on session covering brand identity, illustration and print design fundamentals.'],
    schedule: [{ time: '10:00 AM', title: 'Welcome & materials' }, { time: '1:00 PM', title: 'Lunch break' }],
    lineup: [{ name: 'Naliaka Wanjiru', role: 'Facilitator' }],
    organizer: sondeka,
    ticketTiers: [{ id: 'ga', name: 'Workshop pass', price: 2500, description: 'Materials included', remaining: 6, popular: true }],
    status: 'lowstock',
  },
  {
    id: 'food-culture-festival',
    title: 'Food & Culture Festival',
    category: 'Food & Drink',
    dateTime: '2026-09-19T11:00:00',
    venue: { name: 'Ngong Racecourse', address: 'Ngong Road, Nairobi' },
    priceFrom: 800,
    coverGradient: ['#3F1D0B', '#EA580C'],
    tags: ['Food trucks', 'Family friendly'],
    about: ['A day-long celebration of Kenyan and East African cuisine with live cooking demos and craft stalls.'],
    schedule: [{ time: '11:00 AM', title: 'Gates open' }, { time: '2:00 PM', title: 'Cooking demo stage' }],
    lineup: [],
    organizer: sondeka,
    ticketTiers: [{ id: 'ga', name: 'Day pass', price: 800, description: 'Entry only, food sold separately', remaining: 500 }],
    status: 'onsale',
  },
  {
    id: 'basketball-tournament',
    title: 'Basketball Tournament',
    category: 'Sports',
    dateTime: '2026-09-08T09:00:00',
    venue: { name: 'Nyayo Stadium Annex', address: 'Nyayo Highway, Nairobi' },
    priceFrom: 500,
    coverGradient: ['#052E16', '#16A34A'],
    tags: ['5-on-5', 'Amateur league'],
    about: ['The finals weekend of Nairobi’s biggest amateur 5-on-5 tournament.'],
    schedule: [{ time: '9:00 AM', title: 'Group stage' }, { time: '3:00 PM', title: 'Finals' }],
    lineup: [],
    organizer: sondeka,
    ticketTiers: [{ id: 'ga', name: 'Day pass', price: 500, description: 'All-day access', remaining: 300 }],
    status: 'onsale',
  },
  {
    id: 'sunset-rooftop-session',
    title: 'Sunset Rooftop Session',
    category: 'Parties',
    dateTime: '2026-08-23T17:00:00',
    venue: { name: 'Sankara Rooftop', address: 'Woodvale Grove, Westlands, Nairobi' },
    priceFrom: 1500,
    coverGradient: ['#3B3B44', '#8A8A9E'],
    tags: ['Sundowner', 'Deep house'],
    about: ['A rooftop sundowner session — cancelled by the organizer due to weather.'],
    schedule: [],
    lineup: [],
    organizer: sondeka,
    ticketTiers: [{ id: 'ga', name: 'General', price: 1500, description: 'General admission', remaining: 0, soldOut: true }],
    status: 'soldout',
  },
];

export const EVENT_CATEGORIES: { name: string; count: number }[] = [
  { name: 'Music', count: 312 },
  { name: 'Parties', count: 184 },
  { name: 'Conferences', count: 96 },
  { name: 'Sports', count: 78 },
  { name: 'Comedy', count: 54 },
  { name: 'Food & Drink', count: 143 },
  { name: 'Arts & Culture', count: 121 },
  { name: 'Business', count: 88 },
  { name: 'Technology', count: 67 },
  { name: 'Workshops', count: 102 },
  { name: 'Family', count: 45 },
  { name: 'Networking', count: 73 },
];
